name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Print a greeting
      env:
        MY_VAR: my-tag
      run: |
        echo $MY_VAR

    - name: Is it set here
      run: |
        echo ${{ env.MY_VAR }} is not again

    - name: Publish Docker Action
      uses: jerray/publish-docker-action@v1.0.3
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       # Docker registry server address
       #registry: https://registry.hub.docker.com
       repository: iremmats/hello-github-actions 
       # Docker file used to build image
       file: Dockerfile
       # Docker build context
       path: .
       # Static image tag list, separated by comma
       tags: ${{ env.MY_VAR }} # optional, default is latest
       # Docker build-time variables, separated by comma
       #build_args: # optional
       # If allow pull request trigger build
       #allow_pull_request: # optional
       # Generate tags by conditions automatically
       #auto_tag: # optional
       # Images to consider as cache sources
       #cache: # optional
